# Copyright 2024 Thales
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#==============================================================================#
# This container image is based on the GoLang Debian officical image and
# and embarks libxml2 (from http://xmlsoft.org/download/?C=M;O=D) used by 
# https://github.com/terminalstatic/go-xsd-validate
#
# This container image embarks an openssh-server so that you can connect to it
# thanks to vscode SSH extension. Start it with "service ssh start".
#==============================================================================#

# Set Go & tools versions
ARG GOLANG_VERSION=1.22.5

# Builder image's registry
ARG BUILDER_IMAGE_REGISTRY=docker.io/library
ARG BUILDER_IMAGE_NAME=golang
ARG BUILDER_IMAGE_TAG=${GOLANG_VERSION}-bookworm

# For OCI labels
ARG BASE_REGISTRY=${BUILDER_IMAGE_REGISTRY}
ARG BASE_IMAGE=${BUILDER_IMAGE_NAME}
ARG BASE_IMAGE_TAG=${BUILDER_IMAGE_TAG}

# non-root user
ARG APP_USER="cyclonedx-go"
ARG APP_USER_UID="1234"
ARG APP_GROUP="cyclonedx-go"
ARG APP_GROUP_GID="5678"

#==============================================================================#
# Go Debian image with support for both linux/amd64 and linux/arm64
#==============================================================================#
FROM ${BUILDER_IMAGE_REGISTRY}/${BUILDER_IMAGE_NAME}:${BUILDER_IMAGE_TAG} AS builder-base

# Install openssh-server to be able to connect to the container with vscode SSH extension
RUN apt-get update && apt-get install -y \
        wget \
        openssh-server \
    && rm -rf /var/lib/apt/lists/*

# Configure the SSH Server
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

#==============================================================================#
# Install libxml2 dev used by https://github.com/terminalstatic/go-xsd-validate
#==============================================================================#
FROM builder-base AS libxml2

RUN wget http://xmlsoft.org/download/libxml2-2.9.12.tar.gz \
 && tar -xf libxml2-2.9.12.tar.gz \
 && cd libxml2-2.9.12 \
 && ./configure --prefix=/usr  --enable-static --with-threads --with-history \
 && make \
 && make install

#==============================================================================#
# Final cyclonedx-go dev image
#==============================================================================#
FROM libxml2 AS final

# are defined at the begining og the file
ARG APP_USER
ARG APP_GROUP
ARG APP_USER_UID
ARG APP_GROUP_GID

# create a non-root user
RUN addgroup \
    --gid ${APP_GROUP_GID} \
    ${APP_GROUP} \
 && adduser \
    --uid ${APP_USER_UID} \
    --gid ${APP_GROUP_GID} \
    --shell /bin/bash \
    --disabled-login \
    --disabled-password \
    --gecos "User for cyclonedx-go" \
    ${APP_USER}

#USER ${APP_USER}

ENTRYPOINT ["/bin/bash"]

# See https://github.com/opencontainers/image-spec/blob/main/annotations.md
ARG LABEL_CREATED=""
ARG LABEL_AUTHOR="Thales Open Source <oss@thalesgroup.com>"
ARG LABEL_URL=""
ARG LABEL_DOCUMENTATION=""
ARG LABEL_SOURCE=""
ARG LABEL_VERSION=""
ARG LABEL_REVISION=""
ARG LABEL_VENDOR=""
ARG LABEL_LICENSES="Apache 2.0"
ARG LABEL_TITLE="cyclonedx-go development environment"
ARG LABEL_REF_NAME=""
ARG LABEL_DESCRIPTION="cyclonedx-go development environment with libxml2 (from http://xmlsoft.org/download/?C=M;O=D)"
ARG LABEL_BASE_DIGEST=""
ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_IMAGE_TAG
ARG LABEL_BASE_NAME="${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_IMAGE_TAG}"
LABEL org.opencontainers.image.created="${LABEL_CREATED}"
LABEL org.opencontainers.image.authors="${LABEL_AUTHOR}"
LABEL org.opencontainers.image.url="${LABEL_URL}"
LABEL org.opencontainers.image.documentation="${LABEL_DOCUMENTATION}"
LABEL org.opencontainers.image.source="${LABEL_SOURCE}"
LABEL org.opencontainers.image.version="${LABEL_VERSION}"
LABEL org.opencontainers.image.revision="${LABEL_REVISION}"
LABEL org.opencontainers.image.vendor="${LABEL_VENDOR}"
LABEL org.opencontainers.image.licenses="${LABEL_LICENSES}"
LABEL org.opencontainers.image.title="${LABEL_TITLE}"
LABEL org.opencontainers.image.ref.name="${LABEL_REF_NAME}"
LABEL org.opencontainers.image.description="${LABEL_DESCRIPTION}"
LABEL org.opencontainers.image.base.digest="${LABEL_BASE_DIGEST}"
LABEL org.opencontainers.image.base.name="${LABEL_BASE_NAME}"
